name:                post-photo-to-tumblr
version:             0.1.0.0
license:             AGPL-3
author:              Benjamin Summers
maintainer:          github@bsummers.me
copyright:           2017 Benjamin SUmmers
category:            Web

dependencies:
  - aeson
  - authenticate-oauth
  - base
  - classy-prelude
  - containers
  - foundation
  - http-client
  - http-conduit
  - humblr
  - lens
  - lens-aeson
  - resourcet

executable:
  source-dirs:      .
  main:             post-photo-to-tumblr.hs
