name:                papers-on-ipfs
version:             0.1.0.0
license:             AGPL-3
author:              Benjamin Summers
maintainer:          github@bsummers.me
copyright:           2017 Benjamin SUmmers
category:            Web

executable:
  source-dirs:      src
  main:             Main.hs

dependencies:
  - aeson
  - attoparsec
  - attoparsec-conduit
  - authenticate-oauth
  - base
  - bytestring
  - classy-prelude
  - conduit
  - conduit-extra
  - containers
  - foundation
  - http-client
  - http-conduit
  - http-types
  - lens
  - lens-aeson
  - monad-control
  - mono-traversable
  - mtl
  - old-locale
  - process
  - resourcet
  - time
  - unordered-containers
  - url
  - wreq
  - scotty
  - f-var
  - binary-orphans

default-extensions:
  - DoAndIfThenElse
  - FlexibleContexts
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables
  - TypeApplications
  - UnicodeSyntax
