name:                fatty-prelude
version:             0.1.0.0
license:             BSD3
author:              "Benjamin Summers"
maintainer:          "github@bsummers.me"
copyright:           "2018 Benjamin Summers"

library:
  source-dirs: src

dependencies:
  - base
  - classy-prelude-conduit
  - lens
  - turtle
  - rio
